# Generated by Django 2.1.7 on 2019-03-12 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plproject', '0003_car_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='km',
            field=models.IntegerField(),
        ),
    ]
